### ISSUE TITLE
Pagina inicial

### ISSUE THREAD

**Issue by arthurritzel** [Grupo04-Biopark/queijos-finos#8]
## Descrição
  A pagina inicial é a primeira a ser vista na entrada do sistema, ela será composta por:  um quadrante que contenha as ultimas três propriedades cadastradas e um botão de visualizar propriedades que quando clicado o usuário é encaminhado para tela de propriedades. Ainda na tela inicial, ela deve apresentar um gráfico de pizza que mostre a quantidade de propriedades ativas, desistentes e ativas em complementação.

## Possíveis impedimentos
  Não foi identificado nenhum possível impedimento

## Passo a passo
  1. Definir os controllers de onde os dados serao capturados
  2. Montar a camada de visualização
  3. incluir os controllers a camada de visualiação com o tratamento de dados

**Comment by VitorLimma** [comment]
Card em reta final, entrega será realiada até 04/06.

**Comment by VitorLimma** [comment]
pagina inicial desenvolvida, estou realizando os ajustes finais, segue imagem

![Image](https://github.com/Grupo04-Biopark/queijos-finos/assets/150371637/129b4059-fae0-4632-8fac-70626af1c4cc)
